-- Medicine master expansion (MARG-style attributes + 7-tab fields)
DO $$ BEGIN CREATE TYPE "MedicineStatus" AS ENUM ('CONTINUE','DISCONTINUE','INACTIVE'); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN CREATE TYPE "MedicineType" AS ENUM ('NORMAL','CONTROLLED','OTC','PRESCRIPTION'); EXCEPTION WHEN duplicate_object THEN NULL; END $$;

ALTER TABLE "Medicine" ADD COLUMN IF NOT EXISTS "status" "MedicineStatus" NOT NULL DEFAULT 'CONTINUE';
ALTER TABLE "Medicine" ADD COLUMN IF NOT EXISTS "medicineType" "MedicineType" NOT NULL DEFAULT 'NORMAL';
ALTER TABLE "Medicine" ADD COLUMN IF NOT EXISTS "shortName" TEXT;
ALTER TABLE "Medicine" ADD COLUMN IF NOT EXISTS "fastSearchName" TEXT;
ALTER TABLE "Medicine" ADD COLUMN IF NOT EXISTS "description" TEXT;
ALTER TABLE "Medicine" ADD COLUMN IF NOT EXISTS "composition" TEXT;
-- Units & packaging
ALTER TABLE "Medicine" ADD COLUMN IF NOT EXISTS "packing" TEXT;
ALTER TABLE "Medicine" ADD COLUMN IF NOT EXISTS "primaryUnit" TEXT NOT NULL DEFAULT 'PCS';
ALTER TABLE "Medicine" ADD COLUMN IF NOT EXISTS "secondaryUnit" TEXT;
ALTER TABLE "Medicine" ADD COLUMN IF NOT EXISTS "conversionFactor" DOUBLE PRECISION NOT NULL DEFAULT 1;
ALTER TABLE "Medicine" ADD COLUMN IF NOT EXISTS "boxQuantity" INTEGER;
ALTER TABLE "Medicine" ADD COLUMN IF NOT EXISTS "decimalAllowed" BOOLEAN NOT NULL DEFAULT false;
-- Pricing
ALTER TABLE "Medicine" ADD COLUMN IF NOT EXISTS "rateA" DOUBLE PRECISION;
ALTER TABLE "Medicine" ADD COLUMN IF NOT EXISTS "rateB" DOUBLE PRECISION;
ALTER TABLE "Medicine" ADD COLUMN IF NOT EXISTS "rateC" DOUBLE PRECISION;
ALTER TABLE "Medicine" ADD COLUMN IF NOT EXISTS "defaultPurchasePrice" DOUBLE PRECISION;
ALTER TABLE "Medicine" ADD COLUMN IF NOT EXISTS "defaultCostPrice" DOUBLE PRECISION;
ALTER TABLE "Medicine" ADD COLUMN IF NOT EXISTS "marginPercent" DOUBLE PRECISION;
ALTER TABLE "Medicine" ADD COLUMN IF NOT EXISTS "taxType" TEXT NOT NULL DEFAULT 'TAXABLE';
ALTER TABLE "Medicine" ADD COLUMN IF NOT EXISTS "cess" DOUBLE PRECISION NOT NULL DEFAULT 0;
-- Inventory defaults
ALTER TABLE "Medicine" ADD COLUMN IF NOT EXISTS "defaultReorderLevel" INTEGER NOT NULL DEFAULT 10;
ALTER TABLE "Medicine" ADD COLUMN IF NOT EXISTS "minStock" INTEGER;
ALTER TABLE "Medicine" ADD COLUMN IF NOT EXISTS "maxStock" INTEGER;
ALTER TABLE "Medicine" ADD COLUMN IF NOT EXISTS "negativeAllowed" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "Medicine" ADD COLUMN IF NOT EXISTS "isHidden" BOOLEAN NOT NULL DEFAULT false;

CREATE INDEX IF NOT EXISTS "Medicine_status_idx" ON "Medicine"("status");
